### ISSUE TITLE
Eroare pe local

### ISSUE THREAD

**Issue by cezarneaga** [gov-ithub/asistentul_cetateanului_frontend#23]
#### Expected behavior
widget loading and communicating with Auth0 server
#### Actual behavior
throws error ` index.js:487 Uncaught Error: Error: An error ocurred when fetching data.`
#### Steps to reproduce the problem
```
git pull origin master
npm install
npm start
```
#### Specifications
version of the project: latest   
operating system: mac os sierra   
npm version: 3.10.3  
node version:  v6.7.0

**Comment by cezarneaga** [comment]
solved. it was an .env file error

**Comment by dmfarcas** [comment]
@cezarneaga Am aceasi eroare cu codul de pe master. Cum ai rezolvat? Banuiesc ca nu fac ceva ok in .env
